# Form implementation generated from reading ui file 'passwd.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 457)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(110, 80, 151, 27))
        self.btn_2.setObjectName("btn_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 190, 151, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_3 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)
        self.btn_4 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_4.setObjectName("btn_4")
        self.verticalLayout.addWidget(self.btn_4)
        self.btn_5 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_5.setObjectName("btn_5")
        self.verticalLayout.addWidget(self.btn_5)
        self.btn_6 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_6.setObjectName("btn_6")
        self.verticalLayout.addWidget(self.btn_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 24))
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(parent=self.menubar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionA_Password_Manager_in_Python_is_a_tool_in_which_we_can_add_the_username_and_password = QtGui.QAction(parent=MainWindow)
        self.actionA_Password_Manager_in_Python_is_a_tool_in_which_we_can_add_the_username_and_password.setObjectName("actionA_Password_Manager_in_Python_is_a_tool_in_which_we_can_add_the_username_and_password")
        self.menuabout.addAction(self.actionA_Password_Manager_in_Python_is_a_tool_in_which_we_can_add_the_username_and_password)
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "change user password"))
        self.label_2.setText(_translate("MainWindow", "use these options :"))
        self.btn_2.setText(_translate("MainWindow", "Change password"))
        self.btn_3.setText(_translate("MainWindow", "Add password"))
        self.btn_4.setText(_translate("MainWindow", "View passwords"))
        self.btn_5.setText(_translate("MainWindow", "Delete password"))
        self.btn_6.setText(_translate("MainWindow", "Exit"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.actionA_Password_Manager_in_Python_is_a_tool_in_which_we_can_add_the_username_and_password.setText(_translate("MainWindow", "A Password Manager in Python is a tool in which we can add the username and password"))
