# Form implementation generated from reading ui file 'mp4_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 403)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(60, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.btn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(130, 230, 141, 27))
        self.btn_1.setObjectName("btn_1")
        self.display = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.display.setGeometry(QtCore.QRect(50, 110, 301, 101))
        self.display.setObjectName("display")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 300, 301, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_2 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout.addWidget(self.btn_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 24))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.menuabout = QtWidgets.QMenu(parent=self.menuhelp)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionThis_program_separates_the_audio_from_the_video = QtGui.QAction(parent=MainWindow)
        self.actionThis_program_separates_the_audio_from_the_video.setObjectName("actionThis_program_separates_the_audio_from_the_video")
        self.menuabout.addAction(self.actionThis_program_separates_the_audio_from_the_video)
        self.menuhelp.addAction(self.menuabout.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "Convert MP4 To MP3 "))
        self.btn_1.setText(_translate("MainWindow", "Select MP4 File"))
        self.btn_2.setText(_translate("MainWindow", "Convert"))
        self.btn_3.setText(_translate("MainWindow", "Exit"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.actionThis_program_separates_the_audio_from_the_video.setText(_translate("MainWindow", "This program separates the audio from the video."))
