# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 401)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.display = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.display.setGeometry(QtCore.QRect(50, 40, 301, 91))
        self.display.setObjectName("display")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 150, 221, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_1 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.verticalLayout.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.verticalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 24))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.menuabout = QtWidgets.QMenu(parent=self.menuhelp)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIt_places_each_file_in_its_own_folder = QtGui.QAction(parent=MainWindow)
        self.actionIt_places_each_file_in_its_own_folder.setObjectName("actionIt_places_each_file_in_its_own_folder")
        self.menuabout.addAction(self.actionIt_places_each_file_in_its_own_folder)
        self.menuhelp.addAction(self.menuabout.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_1.setText(_translate("MainWindow", "select folder"))
        self.btn_2.setText(_translate("MainWindow", "start ..."))
        self.btn_3.setText(_translate("MainWindow", "Exit"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.actionIt_places_each_file_in_its_own_folder.setText(_translate("MainWindow", "It places each file in its own folder."))
