from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 746)
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # بخش بالایی - فرم ورودی‌ها
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(255, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        # خط افقی تقسیم کننده
        self.horizontal_line = QtWidgets.QFrame(parent=self.centralwidget)
        self.horizontal_line.setGeometry(QtCore.QRect(50, 400, 464, 20))
        self.horizontal_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.horizontal_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.horizontal_line.setLineWidth(2)
        self.horizontal_line.setStyleSheet("color: #333;")
        self.horizontal_line.setObjectName("horizontal_line")

        # بخش پایینی - مدیریت خطا
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 420, 371, 101))  # تغییر موقعیت به بعد از خط
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 560, 431, 72))  # تغییر موقعیت به بعد از خط
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_5.addWidget(self.textEdit_6)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)

        # ویجت‌های ورودی
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(100, 341, 371, 61))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.widget1)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_4.addWidget(self.textEdit_4)
        self.btn_4 = QtWidgets.QPushButton(parent=self.widget1)
        self.btn_4.setObjectName("btn_4")
        self.horizontalLayout_4.addWidget(self.btn_4)

        self.widget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(150, 240, 291, 61))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.widget2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_3.addWidget(self.textEdit_3)
        self.btn_3 = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout_3.addWidget(self.btn_3)

        self.widget3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(150, 170, 291, 61))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.widget3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.btn_2 = QtWidgets.QPushButton(parent=self.widget3)
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout_2.addWidget(self.btn_2)

        self.widget4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(150, 101, 291, 61))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_1 = QtWidgets.QTextEdit(parent=self.widget4)
        self.textEdit_1.setObjectName("textEdit_1")
        self.horizontalLayout.addWidget(self.textEdit_1)
        self.btn_1 = QtWidgets.QPushButton(parent=self.widget4)
        self.btn_1.setObjectName("btn_1")
        self.horizontalLayout.addWidget(self.btn_1)

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 450, 431, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_6.addWidget(self.textEdit_5)
        self.btn_5 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_5.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.btn_5)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 35))
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(parent=self.menubar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabout = QtGui.QAction(parent=MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menuabout.addAction(self.actionabout)
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", " تعداد شانس :"))
        self.textEdit_6.setPlaceholderText(_translate("MainWindow", "مشکلات"))
        self.label_3.setText(_translate("MainWindow", "مدیریت خطا : "))
        self.textEdit_4.setHtml(_translate("MainWindow", ""))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "عدد مد نظرتون "))
        self.btn_4.setText(_translate("MainWindow", "ثبت"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "تعداد شانس مدنظر"))
        self.btn_3.setText(_translate("MainWindow", "ثبت"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "بازه دوم رو وارد کنید"))
        self.btn_2.setText(_translate("MainWindow", "ثبت"))
        self.textEdit_1.setPlaceholderText(_translate("MainWindow", "بازه اول رو وارد کنید"))
        self.btn_1.setText(_translate("MainWindow", "ثبت"))
        self.btn_5.setText(_translate("MainWindow", "برسی"))

        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "نتیجه"))
        self.menuabout.setTitle(_translate("MainWindow", "درباره"))
        self.actionabout.setText(_translate("MainWindow", "درباره بازی"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())