# Form implementation generated from reading ui file 'keylogger.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 298)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(60, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 140, 141, 31))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 190, 263, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout_2.addWidget(self.btn_3)
        self.btn_1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_1.setObjectName("btn_1")
        self.horizontalLayout_2.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout_2.addWidget(self.btn_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 24))
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(parent=self.menubar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionA_type_of_software_or_hardware_that_is_used_to_monitor_and_record_everything_a_user_types_on_their_keyboard = QtGui.QAction(parent=MainWindow)
        self.actionA_type_of_software_or_hardware_that_is_used_to_monitor_and_record_everything_a_user_types_on_their_keyboard.setObjectName("actionA_type_of_software_or_hardware_that_is_used_to_monitor_and_record_everything_a_user_types_on_their_keyboard")
        self.menuabout.addAction(self.actionA_type_of_software_or_hardware_that_is_used_to_monitor_and_record_everything_a_user_types_on_their_keyboard)
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "   Ready to start?"))
        self.label_2.setText(_translate("MainWindow", "1 : click  start"))
        self.label_3.setText(_translate("MainWindow", "2 : click show_data"))
        self.btn_3.setText(_translate("MainWindow", "close"))
        self.btn_1.setText(_translate("MainWindow", "show_data"))
        self.btn_2.setText(_translate("MainWindow", "start"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.actionA_type_of_software_or_hardware_that_is_used_to_monitor_and_record_everything_a_user_types_on_their_keyboard.setText(_translate("MainWindow", "A type of software or hardware that is used to monitor and record everything a user types on their keyboard."))
